aws-ia/terraform-aws-eks-blueprints-addons

README.md

- Add notice to make it clear that this project is currently under active development
- Ensure this is clear for users that visit the project

chore: Add notice to make it clear that this project is currently under active development

---

modules/eks-blueprints-addon/main.tf

Fix the logic when using condition with role prefix
- Found the problem reviewing the code and input variables

chore: Swap condition when using role prefix

---

modules/irsa/main.tf

fix: Ignore metadata changes on IRSA created namespace for GitOps approach

---

modules/argocd/argocd-application/kubectl/application.yaml.tftpl
modules/argocd/locals.tf
modules/argocd/main.tf

This PR adds support for ArgoCD app recursion: https://argo-cd.readthedocs.io/en/stable/user-guide/directory/#enabling-recursive-resource-detection
- Resolves #73
The following app was created as a result:
```
project: default
source:
repoURL: '.......'
path: cluster-staging/argocd-apps/envs
targetRevision: main
directory:
recurse: true
jsonnet: {}
destination:
server: 'https://kubernetes.default.svc'
namespace: argocd
syncPolicy:
automated:
prune: true
selfHeal: …
```

feat: Support for directory recursion for ArgoCD app added

---

.github/workflows/pr-title.yaml
main.tf
modules/eks-blueprints-addon/main.tf

- Resolves `examples` deployments that were breaking due the `efs_csi_driver` parameter configuration.
- Closes #84 
```bash
~ pre-commit run -a
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for merge conflicts................................................Passed
detect private key.......................................................Passed
detect …
```

fix: Adjusting conditions for EFS CSI Role and Policy creation.

---

tests/complete/main.tf

1. Update EKS cluster version in example to 1.26 (latest)
1. Add example for creating EKS addons for Adot and GuardDuty Runtime Protection (requires manual configuration change in GuardDuty via console, see l[aunch blog](https://aws.amazon.com/blogs/aws/amazon-guardduty-now-supports-amazon-eks-runtime-monitoring/))
- Resolves https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1550
- [] E2E Test successfully complete before merge?

feat: Update cluster version to 1.26 and add all available EKS addons

---

main.tf

bump ingress-nginx helm chart version
Found the update while testing

feat: Bump nginx version

---

.github/workflows/publish-docs.yaml

- Correct version requirement
- Fix my typo
- [x ] Yes, I ran `pre-commit run -a` with this PR

fix: Correct version requirement

---

README.md
docs/architectures.md
mkdocs.yml

- Add table showing supported architectures of the addons provided
- Resolves #161

docs: Add table showing supported architectures of the addons provided

---

docs/aws-fsx-csi-driver.md
docs/cert-manager.md
main.tf

* Adds `docs/aws-fsx-csi-driver`
* Update AWS FSx CSI Driver Helm Chart version to `1.6.0`
* Fix typo on `docs/cert-manager`
Add-ons and examples refactor.
```sh
pre-commit run -a      
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for merge conflicts................................................Passed
detect private key.......................................................Passed
detect aws credentials...................................................Passed
Terraform fmt............................................................Passed
Terraform docs...........................................................Passed
Terraform validate with …
```

chore: Adding `docs/aws-fsx-csi-driver` and updating AWS FSx CSI Driver Helm Chart version to `1.6.0`

---

.pre-commit-config.yaml
docs/aws-fsx-csi-driver.md
mkdocs.yml

- Add FSx doc page to navigation
- Ensure docs are available on webpage

fix: Add FSx doc page to navigation

---

docs/addons/cluster-proportional-autoscaler.md

- Move CPA document to adddons doc directory
- Ensure doc is in correct location to get picked up when publishing

docs: Move CPA document to adddons doc directory

---

tests/README.md
tests/complete/README.md

- Update docs prior to v1 release
- Doc updates

docs: Update docs prior to v1 release

---

docs/addons/external-secrets.md

Correcting the documentation. 

docs: Change the text from dns to secrets

---

README.md

Just adding versioning to readme example 
Want users to leverage versions when extending/using to reduce future potential issues with changes

chore: Updating README.md to include best practice of pinning versions

---

README.md
main.tf

Update addon module from 1.0.0 to 1.1.0 and readme.md
Make use of the default value for Helm release wait argument from true to false from addon module.

feat: Update addon module from 1.0.0 to 1.1.0

---

main.tf

feat: Allow customization of addon parameter chart

---

main.tf

fix: Add "ec2:DescribeTags" IAM permission for api-gateway-controller 

---

main.tf

fix: Update `velero` container image `velero-plugin-for-aws` to `v1.7.1`

---

main.tf

There is a fix for declarative configuration of `authMode` in the latest release which allows argo-workflows to be configured in server, client and sso modes.

feat: Bump argo-workflows chart version

---

main.tf

- Overlap karpenter requirements for both pre < 0.32.x and >= 0.32.x
- In 0.32, nodes are not named based on their hostname by Karpenter. This breaks the IAM policy that requires matching on the pattern `*karpenter*` in the Name tag. A second pattern match of `*compute.internal` has been added for this new behavior
- The chart schema changed in 0.32 to not only drop the `aws` scope from settings, but also some naming changes. To counteract with this, we are doubling up on the values by providing duplicate values that will match both the < 0.32 and >= 0.32 schema. There is one other change that is potentially coming with respect to the prior behavior of providing the IAM instance profile but that is still in progress upstream https://github.com/aws/karpenter/issues/4985
- Resolves #296

feat: Overlap Karpenter requirements to support both pre < 0.32.x and >= 0.32.x

---

main.tf

ASGTerminiate -> ASGTerminate
Fix typo
/NA
/NA

fix: Typo on termination handler

---

docs/addons/fargate-fluentbit.md

Updates documentation for `fargate_fluentbit_cw_log_group` to have the correct retention configuration.
- Resolves #392
- Was something I ran into that took a bit of time to figure out, hoping to save future devs some trouble!

docs: Update docs for retention arguement for fargate_fluentbit_cw_log_group
