README.md
main.tf
modules/external-dns/README.md
modules/external-dns/data.tf
modules/external-dns/main.tf
modules/external-dns/variables.tf
variables.tf

Remove the deprecated variable for external-dns addon
- Resolves #64

chore: Remove external dns deprecated variables

---

modules/external-dns/data.tf

Transfering this fix https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1496 to the new add-on repository.
If you have multiple Route 53 zones on the AWS account, then externalDNS will fail trying to list the resource record sets for other hosted zones (not the one used by your cluster) and won't be able to update even the entry for the zone it has access to.
The issue has appeared after this commit by @rodrigobersa : https://github.com/aws-ia/terraform-aws-eks-blueprints/commit/8421a3b9600b734e600039ec2e8cddf6d03afe83#diff-3972dd5c24a63dda22823ec8ba870f9c566791eeffef91eaa6d6c382fd3fd9d3L97 
So this pull request basically reverts the policy body to the earlier version.
- Resolves #17
I've created a new EKS cluster using ExternalDNS add-on from my fork and the policy was created …

fix: Update ExternalDNS policy to support multiple Route 53 zones

---

README.md
modules/argocd/README.md
modules/argocd/argocd-application/helm/templates/application.yaml
modules/argocd/locals.tf
modules/argocd/main.tf
modules/argocd/outputs.tf
modules/argocd/variables.tf
outputs.tf

This allows the argocd module to be use to generate argocd apps for addons on spoke clusters, skipping the installation of argocd controller on spoke clusters
- Dependency for https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1425

feat: Add support for argocd centralized multi-cluster example

---

modules/external-secrets/data.tf

`ssm:DescribeParameters` seems to need a resource wildcard
Adds IAM permission for external-secrets SA to allow use of `ssm:DescribeParameters` on wildcard resource.
- Resolves aws-ia/terraform-aws-eks-blueprints-addons#75
- replicates PR#1504 https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1504
- not needed
TF plan run
```
~ resource "aws_iam_policy" "external_secrets" {
id          = "arn:aws:iam::<account>:policy/eks-external-secrets-irsa"
name        = "eks-external-secrets-irsa"
~ policy      = jsonencode(
~ {
~ Statement = [
~ {
~ Resource = "arn:aws:ssm:*:*:parameter/*" -> [
+ "arn:aws:ssm:eu-central-1:<account>:parameter/*",
+ "arn:aws:ssm:*:*:parameter/*",
]
},
~ {
~ Resource = "arn:aws:secretsmanager:*:*:secret:*" -> [
+ …
```

fix: Allow external-secret `ssm:DescribeParameters` permission

---

.github/workflows/pr-title.yaml
.github/workflows/pre-commit.yaml
.github/workflows/stale-issue-pr.yaml
README.md
main.tf
modules/eks-blueprints-addon/main.tf
outputs.tf

- Ensure that IAM role creation is tied to overall `create` variable in addons sub-module; setting `create = false` should disable all resource creation
- Set top level GitHub action workflows to `read-all` by default to pass checkov scan
- Resolves #80

fix: Ensure that IAM role creation is tied to overall `create` variable in addons sub-module

---

.github/workflows/pr-title.yaml

- Add `read` permission for PRs to `pr-title` workflow. I think this will work, not sure why the default, top-level `read-all` doesn't work
- Ref: https://github.com/amannn/action-semantic-pull-request/pull/215

fix: Add `read` permission for PRs to `pr-title` workflow

---

.github/workflows/pr-title.yaml
README.md
main.tf
modules/eks-blueprints-addon/README.md
modules/eks-blueprints-addon/main.tf
modules/eks-blueprints-addon/outputs.tf
modules/eks-blueprints-addon/variables.tf

- Add support for creating IAM policies within the addons sub-module
- There are now two primary ways in which permissions can be attached to IRSA roles
- Via `role_policies` which is a map of `{ static-value: policy ARN}` which supports both  existing policies (those where the ARN is known at plan/apply time) such as managed policies, as well as policies which will be created and added during apply (i.e. - custom policies created by users that should be attached to the IRSA role)
- Via the IAM policy created by the addons sub-module. This supports `source_policy_documents`, `override_policy_documents`, and `policy_statements` for multiple methods of passing permissions into the policy that is created and attached to the IRSA role. This route is useful for addons that have a custom policy …

feat: Add support for creating IAM policies within the addons sub-module

---

modules/cluster-autoscaler/data.tf

- Removing a condition that causing a Access Denied error for Cluster Autoscaler pod to talk to EKS API.
- Please checkout the issue #89 for more details
#89

fix: Cluster Autoscaler IRSA policy update to handle Managed Node scaling from Zero 

---

modules/kube-prometheus-stack/main.tf
modules/kube-prometheus-stack/versions.tf

Remove namespace creation to allow deployments to an already-existing namespace. `create_namespace` should be used to create namespaces rather than a resource.
https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/102
- Resolves #102

fix: Remove namespace creation

---

main.tf

- Added a fix for ALB controller addon to set clusterName
- Resolves #105

fix: Added clusterName to alb as its a mandatory value

---

tests/complete/main.tf

chore: Revert back 1.25 as GuardDuty agent not yet available

---

main.tf
variables.tf

- Wrap attribute lookup in `try()` to avoid error when Karpenter is not enabled
- Avoid error when Karpenter is not enabled

fix: Wrap attribute lookup in `try()` to avoid error when Karpenter is not enabled

---

main.tf

1. Uses the correct field when setting the name of the serviceAccountName for the AWS Load Balancer Controller helm chart.
2. Fixes another minor bug in ingress-nginx where we did not create namespace by default.
- Resolves #133

fix: Use correct keys for serviceAccount name for alb chart

---

.pre-commit-config.yaml
main.tf

To resolve [apply failed when not enable Karpenter and/or Velero](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/148).
Create and use the data resource only when enable_karpenter is false.
Update Velero local variables to accept empty string when enable_velero is false.
Executed `terraform plan` with success using the [test](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/blob/main/tests/complete/README.md).

fix: Ensure `karpenter` and `velero` resources are not created when they are not enabled

---

outputs.tf

- Add outputs for AWS resources created for `karpetner` and `aws-node-termination-handler`
- These are necessary to pass to relevant resources, such as the Karpenter provisioner template

feat: Add outputs for AWS resources created for `karpetner` and `aws-node-termination-handler`

---

README.md
main.tf
outputs.tf
tests/complete/main.tf
variables.tf
versions.tf

- Sync updates from testing/validation for v5 changes

chore: Sync updates from testing/validation for v5 changes

---

main.tf

1/ Fixes the FluentBit IAM policy issue for cloudwatch log group with prefix
2/ Fixes the handling of CW Group name and prefix 

fix: Fixed permissions for fluentbit

---

README.md
variables.tf

Fix gatekeeper variable from bool to any
Found the issue while testing

fix: Change gatekeeper variable config to any from bool

---

main.tf
tests/complete/main.tf

Bumps some add-on versions and add update default behavior of VPA to run the admission controller without which it is pretty much useless.
Moved EKS addons to EKS module to use cluster_addons, this makes terraform destroy of addons module less buggy.

chore: Bump add-on versions

---

main.tf

Bump version of aws-cloudwatch-metrics module
Found it while testing

chore: Bump aws-cloudwatch-metrics version to v0.0.9

---

main.tf

Removing old comments that point to deprecated external-secrets project
I like clean things

chore: Removing old comments that reference deprecated external-secrets project

---

.github/workflows/publish-docs.yaml

- Ensure docs CI runs if any CI configurations are made
- Trigger new doc publish

chore: Ensure docs CI runs if any CI configurations are made

---

README.md
helm.tf
outputs.tf
tests/complete/main.tf
variables.tf
versions.tf

- Add generic `helm_releases` variable for provisioning any number of Helm charts
- This addition supports creating an arbitrary number of Helm chart releases which gives users the ability to supplement the module definition with additional Helm charts if not natively supported by the module
- Resolves #168
- Resolves #154
- Resoles #97
- Resolves #47
- Resolves #46

feat: Add generic `helm_releases` variable for provisioning any number of Helm charts

---

README.md
docs/amazon-eks-addons.md
docs/architectures.md
docs/aws-private-ca-issuer.md
main.tf
mkdocs.yml
tests/complete/main.tf
tests/complete/versions.tf
versions.tf

- Update AWS provider min required version to 5.0 to support new EKS addon arguments
- Updates AWS provider to current version, replacing the deprecated argument  `resolve_conflicts` with `resolve_conflicts_on_create` and `resolve_conflicts_on_update`

feat: Update AWS provider min required version to 5.0 to support new EKS addon arguments

---

docs/cluster-proportional-autoscaler.md

Add a readme for installing `cluster-proportional-autoscaler`. This readme is based on https://github.com/aws-ia/terraform-aws-eks-blueprints/blob/main/docs/add-ons/cluster-proportional-autoscaler.md with indentations fixed, validation and testing sections added.
CPA helm chart requires additional values to be passed to be installed. In addition, manual test to observe a scaling event is useful.

chore: Add readme for cluster-proportional-autoscaler installation

---

docs/.pages
docs/helm-release.md

docs: Add helm-release document to explain the different options available

---

main.tf

This PR fixes the `AllowGetCertificates` statement in the IAM policy for ALB controller role.
The included IAM policy for ALB controller sets incorrect permissions for `AllowGetCertificates` statement. It prevents ALB controller from accessing ACM certificates and makes it impossible to use the certificate search functionality, resulting in errors like `AccessDeniedException: User: arn:aws:sts::433222222257:assumed-role/alb-controller-20230620120130875800000002/1687883887660094198 is not authorized to perform: acm:ListCertificates because no identity-based policy allows the acm:ListCertificates action"`
This is a result of limiting the statement to the following resources:
```
"arn:${local.partition}:acm:${local.region}:${local.account_id}:*", …
```

fix: Fix AllowGetCertificates statement scope for ALB controller role

---

.pre-commit-config.yaml
helm.tf
main.tf
tests/complete/README.md
tests/complete/main.tf

- Add permissions for S3 write on FluentBit addons; 
- Add dependency on EKS addon for generic `helm_releases`
- FluentBit supports writing to multiple locations including S3; this adds the permissions to send logs to S3 in addition to Cloudwatch (or not send to CloudWatch and only send to S3 - any combination)
- Since we deploy the EBS CSI driver in the EKS addons, and a number of helm charts require EBS CSI, I've added a dependency between these. I didn't go through and check our other addons, but potentially if they rely on EKS addons such as EBS CSI, then we can add the same dependency on them. This came up when deploying Weaviate using the generic `helm_releases` which requires EBS CSI and it failed since the CSI driver wasn't ready in time

feat: Add permissions for S3 write on FluentBit addons; add dependency on EKS addon for generic `helm_releases`

---

helm.tf

- Set `helm_releases` default value for `wait` to `false`
- This is what we have for the other addons defined here so that we can avoid Terraform timeout errors and instead let the kubernetes controllers/operators resolve the deployment (eventually)

fix: Set `helm_releases` default value for `wait` to `false`

---

main.tf

- No need to read policy if addon disabled

fix: Disable policy data source if the associated addon is disabled

---

README.md
docs/addons/argo-events.md
main.tf
outputs.tf
variables.tf

feat: Add argo events addon module

---

docs/aws-partner-addons.md

Add Amazon FSx for NetApp ONTAP CSI driver as a new partner add-on
Add Amazon FSx for NetApp ONTAP CSI driver as a new partner add-on to the documentation 
New add-on created for Amazon FSx for NetApp ONTAP CSI driver by NetApp as was missing in the docs

docs: Add NetApp ONTAP Astra Trident CSI driver to partner addons

---

main.tf

Upgrade nginx helm chart default version to 4.7.1

feat: Upgrade nginx helm chart to 4.7.1 to support specifying loadBalancerClass

---

main.tf

Fixes conflicting configuration arguments when creating `fargate_fluentbit` Cloudwatch log group, matching behavior of AWS for Fluent-bit configuration.
- Resolves #218

fix: Set either name or name_prefix for fargate_fluentbit log group, not both

---

.pre-commit-config.yaml
main.tf

- Update AWS load balancer controller IAM policy to align with latest policy provided by the LBC project
- Update AWS load balancer controller chart to latest version
- Aligns the policy used here with the policy provided by the LBC project https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/install/iam_policy.json
- Resolves #189
- Resolves #200

feat: Update AWS load balancer controller IAM policy to align with latest policy provided by the LBC project

---

main.tf

1. Adds a check when `karpenter_enable_spot_termination=false` to provide `""` for the value of `interruptionQueue`.
2. Also bumping karpenter version to `0.30.0`
- Resolves #236

fix: Conditional check when spot termination is disabled when karpenter is enabled

---

docs/addons/aws-load-balancer-controller.md
main.tf
tests/complete/main.tf

We do not really have a way to establish an install order of addons. This PR is used to document the issue customers could face when using LBC as it now inserts a mutation webhook for services. As a result addons that have services may timeout waiting for the webhook to be available. Users can safely turn off the webhook if they are not using the `serviceType: LoadBalancer` in any of their software. If they are using it then they should deploy the LBC add-on first. …

docs: Add a note in LBC doc to set enableServiceMutatorWebhook to false

---

README.md
docs/addons/aws-for-fluentbit.md
main.tf
tests/complete/main.tf

* Add support for enabling [Container Insights on Amazon EKS](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-setup-EKS-quickstart.html) through AWS for Fluent Bit module, by replacing the `aws-for-fluent-bit` ConfigMap, based on the template available [here](https://github.com/aws-samples/amazon-cloudwatch-container-insights/blob/main/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/fluent-bit …

feat: Adding support for Container Insights on AWS for Fluent Bit module

---

docs/addons/aws-for-fluentbit.md
main.tf
tests/complete/main.tf

This feature enables the `kubelet` monitoring for ContainerInsights integration with AWS for FluentBit addon, adding the optional requirements shown [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContainerInsights-use-kubelet.html)
- Resolves #231

feat: Adding Kubelet Monitoring feature for ContainerInsights

---

main.tf

We need to have access to the tags on the Route 53 zone.
The addition of `route53:ListTagsForResource` to the external-dns IAM policy.
After having a chat with @csantanapr who informed me of this project I decided to take this project for a spin. There are a few things missing from this project preventing us from using this, this issue being one of them.

feat: Add `route53:listtagsforresource` to `external-dns`

---

.pre-commit-config.yaml
README.md
main.tf

- Update addon module version to skip calling underlying data sources
- Ref https://github.com/aws-ia/terraform-aws-eks-blueprints-addon/pull/21
- If an addon is not created, avoid calling the underlying data sources
- Resolves #261

fix: Update addon module version to skip calling underlying data sources

---

docs/addons/kube-prometheus-stack.md

- Change the repository helm chart from "https://charts.external-secrets.io" to "https://prometheus-community.github.io/helm-charts".
- Change the chart version to the current latest version.
- People interested in trying this add-on will be confused as to why it doesn't work. Since I have noticed it and had that problem, why not help the community with such a simple fix?

docs: Correct Helm chart repository and version of "kube-prometheus-stack" example reference

---

main.tf

Fix `terraform apply` to finish successfully even if `aws_for_fluentbit_cw_log_group.create = false` is set.
- Resolves #270 
Change `source` and check that `terraform apply` is successful.
<details><summary>main.tf</summary><div>
```terraform
terraform {
required_version = ">= 1.5"
required_providers {
aws = {
source  = "hashicorp/aws"
version = ">= 5.0"
}
kubernetes = {
source  = "hashicorp/kubernetes"
version = ">= 2.20"
}
helm = {
source  = "hashicorp/helm"
version = ">= 2.9"
}
time = {
source  = "hashicorp/time"
version = ">=0.9"
}
kubectl = {
source  = "gavinbunney/kubectl"
version = ">= 1.14"
}
}
}
locals {
region = "us-east-2"
}
provider "aws" {
region = local.region
}
data "aws_availability_zones" "available" {}
provider "kubernetes" {
host                   = …
```

fix: Allow `aws_for_fluentbit_cw_log_group.create = false` without error

---

main.tf

Fixes same symptoms from https://github.com/cert-manager/cert-manager/issues/5557
Basically it seems that cert-manager DNS01 for Route53, when configured via Cluster Issuer, is not able to use the SA part of IRSA, but instead needs to assume the role.
- Same symptoms as https://github.com/cert-manager/cert-manager/issues/5557 but not issue in this project yet
- [ X ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)

fix: Allow `cert-manager` IAM role to assume itself

---

.pre-commit-config.yaml
README.md
main.tf
tests/complete/README.md
tests/complete/main.tf
variables.tf

- Update Karpenter addon to support `v0.32.1`/`v1beta1`

feat: Update Karpenter addon to support `v0.32.1`/`v1beta1`

---

.github/workflows/pr-title.yaml
.github/workflows/pre-commit.yaml
.github/workflows/publish-docs.yaml
.github/workflows/stale-issue-pr.yaml

- Update GitHub action workflow versions to latest
- Pin python version for doc publish workflow to 3.11 (3.12 might be a bit too new for the libraries used)
- https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/actions/runs/6722082456/job/18269235482

chore: Update CI versions to latest to fix doc publish workflow

---

.pre-commit-config.yaml
outputs.tf

- Add Karpenter node IAM role name output which is used in v0.32.x+
- Previous versions of Karpenter used the IAM instance profile in the node template, now the EC2NodeClass takes the node IAM role name instead. This exposes that output for consumption downstream in both Terraform and GitOps

fix: Add Karpenter node IAM role name output which is used in v0.32.x+

---

outputs.tf

Add a Terraform output for `fargate_fluentbit` addon, so it can be consumed by other modules.
- Resolves #293 
```
output "fargate_fluentbit" {
value = module.eks_blueprints_addons.fargate_fluentbit
}
```
```
...truncated output
Apply complete! Resources: 58 added, 0 changed, 0 destroyed.
Outputs:
configure_kubectl = "aws eks --region us-west-2 update-kubeconfig --name fargate-fluentbit"
fargate_fluentbit = {
"cloudwatch_log_group" = [
{
"arn" = "arn:aws:logs:us-west-2:xxxxxxxxxxxxx:log-group:/fargate/fargate-fluentbit-logs20231101194544512300000008"
"id" = "/fargate/fargate-fluentbit-logs20231101194544512300000008"
"kms_key_id" = ""
"name" = "/fargate/fargate-fluentbit-logs20231101194544512300000008"
"name_prefix" = "/fargate/fargate-fluentbit-logs"
"retention_in_days" = 90 …
```

feat: Adding `cloudwatch_log_group` resource output

---

main.tf

- Extend more control over Karpenter permissions for 0.32+ changes
- Remove the doubly redundant `!var.karpenter_enable_instance_profile_creation` conditional on the Karpenter instance profile
- With this change, users now have the ability to change the permissions used by the Karpenter IRSA to something like:
```hcl
module "eks_blueprints_addons" {
source = "aws-ia/eks-blueprints-addons/aws"
...
enable_karpenter = true
karpenter = {
irsa_tag_key   = "aws:ResourceTag/karpenter.sh/nodepool"
irsa_tag_value = "*" 
}
}
```
- This change also extends the current value patterns for the `Name` tag value to include `*ec2.internal` which has been reported as another common name pattern
- The instance profile changes is meant to support users migrating from <= 0.31 to 0.32+ where Karpenter starts …

feat: Extend more control over Karpenter permissions for 0.32+ changes

---

main.tf

The [Karpenter documentation](https://karpenter.sh/docs/reference/cloudformation/#:~:text=Copy-,AllowSSMReadActions,-The%20AllowSSMReadActions%20Sid) references less privileges (AWS SSM Parameter Store read access) than what's implemented in the current addon module for karpenter. 
This PR reconciles the current terraform module with what the documentation states.
Follow the principle of least privilege

fix: Restrict Karpenter privileges on AWS SSM parameter store

---

main.tf

gateway-api-controller lacks permissions to do its job
The api gateway controller addon lacks permissions to create httproutes as it currently throwing up errors 
```shell
{"level":"debug","ts":"2023-12-06T23:49:12.024Z","logger":"controller.route","caller":"lattice/target_group_synthesizer.go:81","msg":"Failed TargetGroupManager.Upsert k8s-default-parking due to AccessDeniedException: User: arn:aws:sts::331334982285:assumed-role/aws-gateway-api-controller-20231206231429634800000015/1701904568794509513 is not authorized to perform: tag:GetResources because no identity-based policy allows the tag:GetResources action\n\tstatus code: 400, request id: 884a076d-a781-49e3-8404-7236d80533bd"}
{"level":"debug","ts":"2023-12-06T23:49:12.102Z","logger":"cloud","caller":"aws/cloud.go:58","msg":"error …
```

fix: Gateway-api-controller lacks permissions to create and describe required resources

---

main.tf

This pull request enables users to grant IAM policy permissions to allow Fargate Fluent Bit to send logs to Kinesis Data Firehose
I have encountered this issue. My company requires me to send logs to Kinesis Data Firehose, and I implemented this solution through the aforementioned modification. - Resolves #118

feat: Grant IAM policy permissions to allow Fargate Fluent Bit to send logs to Kinesis Data Firehose

---

docs/amazon-eks-addons.md

This PR simply update the documentation with the recent improvements of managed-addons capabilities for configuration.
Adding a more complete sample on what is possible to configure for coreDNS

docs: Add a full example of CoreDNS ConfigurationSchema

---

.pre-commit-config.yaml
docs/addons/karpenter.md
main.tf

- Change Karpenter instance termination key condition to use more broadly applciable
- On later versions  of karpenter (0.32+), the nodes are named by karpenter which can create conflicts with the current policy. Previous attempts to add additional name pattern globs as well as let users pass in both key and values to suite are still creating friction. Using this tag, which has been around since pre 0.10 Karpenter, should remove that friction for user until the policy defined here is updated to match the upstream project
- Resolves #336
- Resolves #339

fix: Change Karpenter instance termination key condition to use more broadly applciable

---

main.tf

I will make corrections to find spelling mistakes.
I understand that this change only affects the identifiers of resources.
i recreated a PR to merge v2.0 branch ( #344 )
- Resolves #345 
```
~/terraform-aws-eks-blueprints-addons$ pre-commit run -a
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check for merge conflicts................................................Passed
detect private key.......................................................Passed
detect aws credentials...................................................Passed
Terraform fmt............................................................Passed
Terraform docs......................................................... …
```

fix: Correct spelling in the locals.ec2_events

---

main.tf

Adds the `elasticloadbalancing:DescribeTrustStores` IAM policy for the new mTLS feature in LB Controller introduced in [v2.7.0](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.7.0).
- [] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)

feat: MTLS support for LB controller

---

README.md
docs/addons/bottlerocket.md
main.tf
outputs.tf
tests/complete/main.tf
variables.tf

Adding Bottlerocket Update Operator addons for automated CVE patching on Bottlerocket OS based nodes. 
Requested by the Bottlerocket Pattern PR [here](https://github.com/aws-ia/terraform-aws-eks-blueprints/pull/1869)

feat: Bottlerocket Update Operator Addon

---

main.tf

relates to https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/354
- Resolves #354

fix: Reference to optional parameter var.cert_manager.wait

---

.pre-commit-config.yaml
README.md
docs/addons/aws-load-balancer-controller.md
docs/addons/bottlerocket.md
docs/amazon-eks-addons.md
main.tf
tests/complete/README.md
tests/complete/main.tf
tests/complete/versions.tf

- Update default chart versions to latest minor version supported
- Updates default version to pull in recent changes by the supported projects (addons)

feat: Update default chart versions to latest minor version supported

---

.github/workflows/pr-title.yaml
.github/workflows/pre-commit.yaml
.github/workflows/stale-issue-pr.yaml
.pre-commit-config.yaml
main.tf

- Correct cluster autoscaler version typo
- Use the correctm static service principal DNS suffix; we changed this in the EKS module as well since service principals do not change their DNS suffix across partitions
- [Ref 1](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/modules/karpenter/main.tf#L447-L448)
- [Ref 2](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/1627231af669796669ce83e0a4672a7e6d94a0b3/main.tf#L371-L380)
- Remove Terraform cache in CI - not really adding much other than failing checks when lockfile is out of sync
- Resolves #369
- Resolves #371

fix: Correct cluster autoscaler version typo, use (correct) static service principal DNS suffix

---

.pre-commit-config.yaml
README.md
docs/addons/external-secrets.md
main.tf
variables.tf

- Change default `external-secrets` port when addons are deployed on EKS Fargate to avoid port conflict
- Ref https://github.com/external-secrets/external-secrets/issues/1306#issuecomment-1171540600
- Ref https://github.com/external-secrets/external-secrets/issues/1078#issuecomment-1117077327
- Resolves #55

fix: Change default `external-secrets` port when addons are deployed on EKS Fargate to avoid port conflict

---

main.tf

- Add support for GitOps Bridge to Argo Events
- Resolves #377

fix: Add support for gitops-bridge to argo events

---

docs/addons/aws-cloudwatch-metrics.md
docs/addons/aws-efs-csi-driver.md
docs/addons/aws-for-fluentbit.md
docs/addons/aws-fsx-csi-driver.md
docs/addons/aws-load-balancer-controller.md
docs/addons/cert-manager.md
docs/addons/external-dns.md
docs/addons/fargate-fluentbit.md
docs/addons/velero.md
docs/addons/vertical-pod-autoscaler.md

* Remove broken links pointing to old repo with `kubernetes-modules` directory.
* Adding missing links to referred add-on docs
* General formatting fixes.

fix: Removing and updating broken links on `docs/addons`

---

.pre-commit-config.yaml
main.tf

- Change evaluation logic from eager (`try()`) to lazy (`lookup()`) to avoid unknown value errors when iterating over computed values https://github.com/clowdhaus/terraform-for-each-unknown
- Resolves #395

fix: Switch to lazy evaluation for Karpenter node IAM role additional permissions attachment

---

main.tf

Update default version to [v0.37.0](https://github.com/aws/karpenter-provider-aws/releases/tag/v0.37.0)

feat: Update Karpenter default version to `0.37.0`

---

.pre-commit-config.yaml
README.md
tests/complete/README.md

- Add clarifying support disclaimer like the original/main project

chore: Add clarifying support disclaimer like the original/main project

---

main.tf

Updates fargate-fluentbit configMap, to fit the [AWS Docs guidance](https://docs.aws.amazon.com/eks/latest/userguide/fargate-logging.html).
It seems required to have different OUTPUTS for `flb_log_cw` which are the logs for FluentBit itself, and for the applications running on the cluster with proper FILTERS and PARSERS.
- Resolves #412

fix: Fixing fargate-fluentbit configMap to parse logs correctly

---

main.tf

Add support for the latest version of the aws-load-balancer-controller v2.9.0.
See this commit for the IAM changes: https://github.com/kubernetes-sigs/aws-load-balancer-controller/commit/174ad832de5b7a960a3f88b50ee139b80f75190b#diff-18d547fa3761f3fd92e3c94aced34137247a3ebd73b3f547491dffc10859b712R43
Add support for aws-load-balancer-controller [v2.9.0](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.9.0)

feat: Update IAM policy for AWS Load Balancer Controller to support Listener Attributes

---

docs/addons/kube-prometheus-stack.md

Add correct namespace for kube-prometheus-stack doc
- Resolves: fix namespace for kube-prometheus-stack before the namespace was external-secrets

docs: Correct namespace for kube-prometheus-stack

---

.github/workflows/pre-commit.yaml
.pre-commit-config.yaml
README.md
main.tf
tests/complete/README.md
tests/complete/main.tf
tests/complete/versions.tf
variables.tf

- Add ability to track usage telemetry of EKS Blueprint solutions
- Update CI versions to latest
- Remove ADOT; ADOT support is trailing EKS version support quite a bit which makes testing challenging
- Relates to https://github.com/aws-ia/terraform-aws-eks-blueprints/issues/1274

feat: Add ability to track usage telemetry of EKS Blueprint solutions

---

README.md
main.tf
versions.tf

- Add random entryopy to CloudFormation stack name for when module used multiple times on the same cluster
- Relates to #424

fix: Add random entryopy to CloudFormation stack name for when module used multiple times on the same cluster

---

README.md
versions.tf

It's due to this error:
The provider hashicorp/random does not support resource type "random_bytes"
PR that introduced this scenario:
https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/425
Random provider documentation:
https://registry.terraform.io/providers/hashicorp/random/3.6.0/docs
Just bump the required hashicorp/random provider to request at least version `3.6.0` to support  the `random_bytes` resource.
- Resolves #426
```sh
Initializing provider plugins...
- terraform.io/builtin/terraform is built in to Terraform
- Finding hashicorp/random versions matching ">= 3.6.0, ~> 3.6.0"...
...
- Installing hashicorp/random v3.6.3...
- Installed hashicorp/random v3.6.3 (signed by HashiCorp)
...
Terraform has been successfully initialized!
```
`pre-commit run -a`
``` 
$ …
```

fix: Raise min required version of `hashicorp/random` provider to `v3.6`

---

main.tf

Change the `cloudWatchLogs.logGroupName` fluentbit helm chart value to match the created log group. Might not work if the log group doesn't exist, haven't tested this yet etc.
- Resolves #341 
I saw the [this closed PR](https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/409) also fixed the issue and also works when the log group doesn't exist.

fix: Attempt to use created log group for AWS for FluentBit before falling back to an externally created log group name

---

main.tf

Update the policy document for AWS Load Balancer controller to support the latest version v.2.10.0.
See [kubernetes-sigs/aws-load-balancer-controller@`v2.9.2...v2.10.0`#diff-50bbcd5ae0](https://github.com/kubernetes-sigs/aws-load-balancer-controller/compare/v2.9.2...v2.10.0#diff-50bbcd5ae0a29cf3c9e0d5fb5f425bbf7aa961f68bce6133162bfb8ce4eff085R32)
Add support for aws-load-balancer-controller [v2.10.0](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.10.0)

feat: Add `ec2:GetSecurityGroupsForVpc` permission to `aws-load-balancer-controller`

---

main.tf

It adds support for external-secrets bulk fetch feature introduced in [v0.12.1](https://github.com/external-secrets/external-secrets/releases/tag/v0.12.1)
Support for external-secrets [v0.12.1](https://github.com/external-secrets/external-secrets/releases/tag/v0.12.1)

feat: Add `secretsmanager:BatchGetSecretValue` to support external-secrets bulk fetch

---

main.tf

Add support for the latest aws-load-balancer-controller version 2.11.0.
See https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.11.0
Add support for aws-load-balancer-controller [v2.11.0](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.11.0)

feat: Add `elasticloadbalancing:DescribeCapacityReservation` and `elasticloadbalancing:ModifyCapacityReservation` to `aws-load-balancer-controller`

---

main.tf

Adds `path` argument to `aws_iam_policy.fargate_fluentbit`.
I want to be able to provide a custom path for the `fargate_fluentbit` policy to adhere to security constraints within some organisations.
Similar to https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/96

feat: Add policy path to fargate_fluentbit

---

docs/addons/cert-manager.md

Update documentation for the cert-manager addon to include a note about the Fargate kubelet port conflict with cert-manager webhook and how to fix it.
When testing a prototype on Fargate I ran into this issue. Document it so others will benefit.
- [ *] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ *] Yes, I ran `pre-commit run -a` with this PR
Documentation change only, I've validated that the documented fix works.

fix: Document Fargate kubelet cert-manager port conflict

---

main.tf

Bumps ingress-nginx helm version to latest and greatest.
https://kubernetes.io/blog/2025/03/24/ingress-nginx-cve-2025-1974/

feat: Bumping ingress-nginx version

---

docs/addons/velero.md

Update stateful example link
Update the incorrect url that links to the stateful blueprints example
Broken links in docs is an easy first contribution
I am not sure if testing is required to update the docs?

docs: Update velero.md - update link url to stateful example/pattern

---

.pre-commit-config.yaml
README.md
tests/complete/README.md
tests/complete/versions.tf
versions.tf

- Pin Helm provider max supported version due to new major provider version breaking changes
- Recent Helm v3.x introduces breaking changes, theres already a hotfix out https://github.com/hashicorp/terraform-provider-helm/releases. Supporting v3.x would require breaking changes to this module so for now, pinning should suffice

fix: Pin Helm provider max supported version due to new major provider version breaking changes
